version: "3.5"

networks:
  localdev:
    name: localdev

services:
  todos_server:
    build: ./
    image: todos_server:v1
    container_name: todos_server
    ports:
      - 3000:3000
    restart: always
    depends_on:
      - database
    networks:
      - localdev

  database:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    networks:
      - localdev
